name: Release Management

on:
  release:
    types: [published]

jobs:
  release:
    name: Release to gem hosts
    runs-on: ubuntu-latest
    steps:
      - name: Setup ruby
        uses: actions/setup-ruby@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Setup credentials and versioning
        run: |
          gem install git-lite-version-bump keycutter roo
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          printf -- ":github: Bearer ${GPR_API_KEY}\n" >> $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          GPR_API_KEY: ${{secrets.GITHUB_TOKEN}}
      - name: Build gem
        run: rake build_release
      - name: Publish to RubyGems
        run: |
          gem push --KEY rubygems --host https://rubygems.org *.gem
      - name: Publish to GPR
        run: |
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          OWNER: mitre
