name: Generate RELEASE.md
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Generate RELEASE.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout inspec_tools
        uses: actions/checkout@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Get information for RELEASE.md
        run: |
          git pull origin master
          echo "**Release:** " > RELEASE.md
          git describe --tags $(git rev-list --tags --max-count=1) >> RELEASE.md
          echo "<br><br>**Date:** " >> RELEASE.md
          git show -s --format=%ci $(git rev-list --tags --max-count=1) >> RELEASE.md
          echo "<br><br>**Commit:** " >> RELEASE.md
          git rev-list --tags --max-count=1 >> RELEASE.md
          printf "module InspecTools\n  VERSION = '$(git describe --tags $(git rev-list --tags --max-count 1) | grep -o "[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+")'.freeze\nend\n" > lib/inspec_tools/version.rb
      - name: Commit and push changes to RELEASE.md
        uses: Bialogs/commit@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Publish release information'
          force-add: 'true'
        env:
          CI: true
